name: Notify New Version

on:
  push:
    branches:
      - main  # Adjust this to your main branch if needed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from version.txt
        id: read_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Notify deps2.dev
        run: |
          curl -X POST "http://127.0.0.1:5000/v3alpha/systems/npm/packages/veritax/newVersion" \
          -H "Content-Type: application/json" \
          -d '{"version": "${{ env.VERSION }}"}'
